services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    ### hot reload using watch
    develop:
      watch:
        - action: sync
          path: .
          target: /app
    ### hot reload using volumes
    # volumes:
    #   - ./web:/app
    #   - /app/node_modules
    # environment:
    # - CHOKIDAR_USEPOLLING=true
    # - WATCHPACK_POLLING=true