FROM node:23-bookworm-slim AS build

WORKDIR /app

COPY package*.json ./

RUN npm ci --omit=dev --ignore-scripts

COPY . .

RUN npm run build

# SET NODE_ENV to production
ENV NODE_ENV=production

# Production Stage
FROM nginx:stable-alpine3.21-slim AS production

# Patch OpenSSL (fixes CVE-2025-9230)
RUN apk update && apk upgrade --no-cache libcrypto3 libssl3 openssl

# # Copy Nginx config if you have custom routing
# COPY ./nginx.conf /etc/nginx/nginx.conf

COPY --from=build /app/dist /usr/share/nginx/html

# Copy the runtime injection script into the container
COPY env.sh /docker-entrypoint.d/env.sh
RUN dos2unix /docker-entrypoint.d/env.sh
RUN chmod +x /docker-entrypoint.d/env.sh

EXPOSE 80
# Let Docker run your script before starting Nginx
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]